### ISSUE TITLE
Proposal: change 'Tabs' to 'TabBar' in user.cfg

### ISSUE THREAD

**Issue by luzpaz** [triplus/TabBar#2]
Currently working on this [gist](https://gist.github.com/luzpaz/1f1ad4b78c20465c43d6721f11966acc) that is documenting how `user.cfg` is structured. I've been looking at the configs of TabBar. 

My idea is to keep the user.cfg as readable as possible, so keeping with your 'brand recognition' I think it makes sense to change the generic word **Tabs** in both:

```xml
        <FCParamGroup Name="Toolbars">
          <FCBool Name="Tabs" Value="1"/>
        </FCParamGroup>
```
and
```xml
      <FCParamGroup Name="PersistentToolbars">
        <FCParamGroup Name="User">
          <FCParamGroup Name="StartWorkbench">
            <FCBool Name="Saved" Value="1"/>
            <FCText Name="Top">Break,File,Workbench</FCText>
            <FCText Name="Left"></FCText>
            <FCText Name="Right"></FCText>
            <FCText Name="Bottom">Tabs</FCText>
          </FCParamGroup>
```

to **TabBar**

What do you think?

Edit: Any idea why the latter is in `StartWorkbench`?

**Comment by triplus** [comment]
Persistent toolbars is a piece of functionality, that manages toolbar position in FreeCAD. Without it specific workbench toolbar position gets lost, on each FreeCAD restart. It's a part of the Tux module. Any toolbar, not just the Tabs one, can get listed under its settings. 

As for TabBar vs. Tabs, name of the toolbar. It was TabBar in the past, but i opted in using more user friendly name at some point of development. Currently i have no plans to rename the toolbar.

**Comment by luzpaz** [comment]
Thanks. 
I get the Persistent Toolbar idea, my question is what is StartWorkbench? 
why is it in PersistentToolbars ?
and why are toolbar settings in it ?

**Comment by triplus** [comment]
You have moved the Tabs toolbar to the bottom of the main window in the Start workbench. That is what the saved parameters tell me. Next time you will start FreeCAD, or activate Start workbench, toolbars will get positioned based on the previously saved parameters. I don't see any TabBar module specific settings.

**Comment by triplus** [comment]
Nothing to do here, hence closing.
