### ISSUE TITLE
Installing TabBar resets FreeCAD settings

### ISSUE THREAD

**Issue by ifohancroft** [triplus/TabBar#3]
I just installed TabBar on FreeCAD from the Addon Manager, restarted FreeCAD and my settings were reset.

OS: Manjaro Linux (MATE/mate)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24169 (Git)
Build type: Release
Branch: master
Hash: eb240c219c1966e53aae24de0060c002b860c3af
Python version: 3.9.1
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/United States (en_US)

**Comment by goyalyashpal** [comment]
Not reproduced on installing Tabbar today from FreeCAD addon manager.

Settings verified to stay intact:
* general > document
* display > colors

```
OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24267 +99 (Git)
Build type: Release
Branch: Branch_0.19.3
Hash: 6530e364184ce05ccff39501e175cf2237e6ee4b
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.3
Locale: English/United States (en_US)
```

**Comment by ifohancroft** [comment]
I should have probably specified that some of the settings that it reset were moved toolbars, hidden toolbars, etc. I can't remember what other settings it reset at the time.

**Comment by goyalyashpal** [comment]
> moved toolbars

stil not reproduced.

i had moved the sketcher toolbars (elements and constraints), and similarly the part design toolbar (features) to the right corner (vertically) before installing that, and they stayed there after installing, did not reset.

**Comment by ifohancroft** [comment]
Since you can't reproduce it and I had the problem a long ass time ago, I am guessing something in FreeCAD changed. I.e. maybe it was something in FreeCAD that was causing it.
I guess this report should just be closed.
